version: "3"

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
#    depends_on:
#      - mongo
    image: lucatk/infisical-backend-windows
    ports:
      - '4000:4000'
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  frontend:
    container_name: infisical-frontend
    restart: unless-stopped
    depends_on:
      - backend
    image: lucatk/infisical-frontend-windows
    ports:
      - '4040:3000'
    env_file: .env
    environment:
      # - NEXT_PUBLIC_POSTHOG_API_KEY=${POSTHOG_PROJECT_API_KEY}
      - INFISICAL_TELEMETRY_ENABLED=${TELEMETRY_ENABLED}
      - NEXT_PUBLIC_STRIPE_PRODUCT_PRO=${STRIPE_PRODUCT_PRO}
      - NEXT_PUBLIC_STRIPE_PRODUCT_TEAM=${STRIPE_PRODUCT_TEAM}
      - NEXT_PUBLIC_STRIPE_PRODUCT_STARTER=${STRIPE_PRODUCT_STARTER}
    networks:
      - infisical

#  didn't work for me (volume bind mount bug)
#  use: docker run --env-file .env --restart=always --network infisical_infisical --name infisical-mongo -v infisical-mongo-data:c:\data\db mongo:nanoserver-1809
#
#  mongo:
#    container_name: infisical-mongo
#    image: mongo:windowsservercore-1809
#    restart: always
#    env_file: .env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
#    volumes:
#      - 'mongo-data:c:\data\db'
#    networks:
#      - infisical

volumes:
  mongo-data:
    driver: local

networks:
  infisical:
